baseurl = "https://quanteda.io/"
title = "quanteda: R package for quantitative analysis of textual data"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-144616-23"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 3

#[[menu.main]]
#    name = "FAQ"
#    identifier = "faq"
#    url  = "/faq/"
#    weight = 4

# Top bar social links menu (not used)

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/quanteda/"
    pre = "<i class='fab fa-2x fa-github'></i>"

#[[menu.topbar]]
#    weight = 2
#    name = "Facebook"
#    url = "http://facebook.com"
#    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/textasdata"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "YouTube"
    url = "https://www.youtube.com/channel/UC0xc75IqmteIlp-i2vjKWFg"
    pre = "<i class='fab fa-2x fa-youtube'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "quanteda team"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "News about quanteda project"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    about_us = "**quanteda** is developed by [a team of developers](/about/) through the Quanteda Initiative."
    copyright = "Copyright (c) 2017-2018 Quanteda Initiative; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

[Permalinks]
    news = "/news/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = "quanteda initiative"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "Here are some of the [testimonials](https://github.com/kbenoit/quanteda/issues/461) left by our users, in their own words."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    title = "Our users"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "News"
    subtitle = ""
